src/Entity/Post.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PostRepository")
 */
class Post
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_update;
    
    public function __construct() {
        $this->date_update = new \DataTime;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle(string $title)
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription()
    {
        return $this->description;
    }

    public function setDescription(string $description)
    {
        $this->description = $description;

        return $this;
    }


    public function getDateUpdate()
    {
        return $this->date_update->format('Y-m-d H:i:s');
    }

    public function setDateUpdate(\DateTimeInterface $date_update)
    {
        $this->date_update = $date_update;

        return $this;
    }
}

src/Controller/Blog.php
<?php
namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
//use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Post;

class Blog extends AbstractController
{    
    /**
     * @Route("/", name="list")
     */
    public function listPosts()
    {
        $em = $this->getDoctrine()->gerManager();
        $posts = $em->getRepository(Post::class)->findAll();
        var_dump($posts[0]->getTitle());
        
        return $this->render('posts/list.html.twig',[
            "posts" => $posts
         ]);   
    }
    
    
    /**
     * @Route("/post/{id}/edit", name="edit", methods={"GET"})
     */
    public function editPost(int $id)
    {
        var_dump($id);
        return $this->render('posts/edit.html.twig');
    }
    
     /**
     * @Route("/post/add", name="add", methods={"GET"})
     */
    public function addPost()
    {
        return $this->render('posts/add.html.twig');
    }
    
     /**
     * @Route("/post/save", name="save", methods={"POST"})
     */
    public function savePost()
    {
        $title = $_POST['title'];
        $description = $_POST['description'];
        $em = $this->getDoctrine()->gerManager();
        
        $Post = new Post();
        $Post->setTitle($title);
        $Post->setDescription($description);
        
        $em->persist($Post);
        $em->flush();
       
//        $em = $this->getDoctrine()->getManager();
//        $post = $em->find(Post::class, 1);
        
         return $this->render();
         }
    
    /**
     * @Route("/post/{id}", name="show", methods={"GET"})
     */
    public function showPost(int $id)
    {
        var_dump($id);
        return $this->render('posts/show.html.twig');
    }
    
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link href="/style.css" rel="stylesheet"/>
{#        <script defer src="/anime.min.js"></script>
        <script defer src="/main.js"></script>#}
        
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        <header>
            <div class="header-wrap"> 
            <div class="logo"> Blog posts
                {#<div class="ferro"></div>#}
            </div>
            </div>         
        </header>

        <div class="page">
            {% block body %}{% endblock %}
        </div>
        <footer>  
            Web dev pushkining 2020
        </footer>
            {% block javascripts %}{% endblock %}
    </body>
</html>

templates/posts/add.html.twig
{# empty Twig template #}
{% extends "base.html.twig" %}

{% block body %}
    <h1>Add post</h1>
    <form action="/post/add" method="POST" class="post-form"> 
        <label>
            Enter title
            <input name="title" type="text"/>
        </label>
         <label>
            Enter discription
            <textarea name="discription"></textarea>
        </label>
        <button class="btn-blue">Create post<button>
    </form>
{% endblock %}

templates/posts/edit.html.twig
{# empty Twig template #}
{% extends "base.html.twig" %}

{% block body %}
    <h1>Edit post</h1>
{% endblock %}

templates/posts/list.html.twig
{# empty Twig template #}
{% extends "base.html.twig" %}

{% block body %}
    <h1>List posts</h1>
    <a class="btn" href="/post/add">Add post</a>
    <div class="post-list" >
        {% for post in posts %}
        <div class="post">
        <h3>{{ post.title }}</h3>
        <i>{{ post.dateUpdate }}</i>
        <p>{{ post.description }}</p>
        
        </div>
    {% endfor %}
    </div>
{% endblock %}

templates/posts/show.html.twig
{# empty Twig template #}
{% extends "base.html.twig" %}

{% block body %}
    <h1>Show post/h1>
{% endblock %}

templates/posts/success.html.twig
{# empty Twig template #}
{% extends "base.html.twig" %}

{% block body %}
    <h1>List posts</h1>
    <a class="btn" href="/">Add post Success</a>
{% endblock %}